/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is committed here so
// the phase-two scaffold typechecks cleanly after dependencies are installed.

